pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - status-success="build"
    actions:
      merge:
        method: merge
pull_request_rules:
  - name: Automatic merge for Silasary
    conditions:
      - author=silasary
      - status-success="build"
    actions:
      merge:
        method: merge
pull_request_rules:
  - name: Automatic merge for Dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success="build"
    actions:
      merge:
        method: merge
